### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by alxbilger**
According to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### CODE REVIEW

**Comment by fredroy** [comment]
You may need to update the branch v4 as well, as it is the most used by the other project

**Comment by alxbilger** [comment]
I noticed that dd70857e1846acb81869ceed20d1ca0760f1db0f is not in v4. What do you want to do about it?

**Comment by alxbilger** [comment]
@hugtalbot @fredroy I don't have the write access to merge this PR

**Comment by alxbilger** [comment]
Probably because Windows 2016 is requested, and I am not sure it is still supported

**Comment by alxbilger** [comment]
Let's see if https://github.com/sofa-framework/sofa-setup-action/pull/3 works, and then we can merge it in this PR

**Comment by alxbilger** [comment]
@hugtalbot Windows builds are ok now. I merge

**Review by Aldana-15 — APPROVED** [review]

**Pull request merged**
